### ISSUE TITLE
issue in execution

### ISSUE THREAD

**Issue by shaikhahmad** [zhuoyunli/Implementation-of-Learning-without-Forgetting-for-multi-class#1]
I'm have following error in execution 

AttributeError                            Traceback (most recent call last)

<ipython-input-5-18014c94f79b> in <module>()
     14 
     15 for i in range(10):
---> 16     model.beforeTrain()
     17     accuracy=model.train()
     18     model.afterTrain(accuracy)

/content/LwF.py in beforeTrain(self)
     52     def beforeTrain(self):
     53         self.model.eval()
---> 54         classes=[self.numclass-self.task_size,self.numclass]
     55         self.train_loader,self.test_loader=self._get_train_and_test_dataloader(classes)
     56         if self.numclass>self.task_size:

AttributeError: 'LwFmodel' object has no attribute 'task_size'

**Comment by DRSAD** [comment]
Sorry, the bug has been fixed. The task_size attribute is used to indicate the category that is incremented each time.

The data I give is not fully fitted on resnet18, you can add more epochs to fit
